### ISSUE TITLE
[Feature request] Print shortcut

### ISSUE THREAD

**Issue by TandersT** [ArturKovacs/emulsion#131]
I find that I miss being able to press ctrl+p to print something. It would be beneficial for me, not sure how necessary it is as a whole though.

**Comment by ArturKovacs** [comment]
Yeah this seems like something that would fit Emulsion. The question is if it's possible to bring up an OS-native printing dialogue on all supported platforms; and is there a lightweight crate that can do that.

If there isn't such a crate, but it's possible, then bringing up the printing dialogue can be built into gelatin (I'm not sure if it would be good to create a separate crate for this.)

**Comment by ArturKovacs** [comment]
I'm not sure if this is possible to do in a cross-platform, yet lightweight manner. In the meantime here's a hacky solution for windows. If you add the following to your [`cfg.toml`](https://arturkovacs.github.io/emulsion-website/configuration.html) file, then <kbd>Ctrl</kbd>+<kbd>P</kbd> will open up the standard Windows image-printing-dialogue. One caveat is that there's also a PowerShell window appearing which you have to manually close when you are done printing. I could not find a way to autmatically close the PS window.

```toml
[[commands]]
input = ["ctrl+p"]
program = "cmd"
# Below we load WPF and create a dummy window (not visible) just so that the following
# Start-Process invocation can show a DPI aware print-dialogue, so it's not blurry on HiDPI displays.
# This idea was taken from: https://stackoverflow.com/questions/63907191/powershell-dpi-aware-form
args = ["/C", "start", "", "powershell", "-NoExit", "-Command", "Add-Type -AssemblyName \"PresentationFramework\"; [xml]$Xaml = '<Window xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\" xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\" x:Name=\"Window\"></Window>'; $Reader = (New-Object System.Xml.XmlNodeReader $Xaml);$Window = [Windows.Markup.XamlReader]::Load($Reader); Start-Process -FilePath \"${img}\" -Verb Print"]
```
