### ISSUE TITLE
Fullscreen keyboard toggle

### ISSUE THREAD

**Issue by tuncer** [ArturKovacs/emulsion#30]
I wanted to implement fullscreen toggle via keyboard and saw that it is ~~semi-implemented~~ already. Thus, before I make the wrong diff, let's discuss how you'd like fullscreen toggle to work. Should the binding be configurable? What about key handling in picture_widget and picture_panel, meaning, where should it be implemented?

**Comment by ArturKovacs** [comment]
Currently doub-clicking with the left mouse button toogles fullscreen mode so I'm not sure what you mean by semi-implemented. Although making the binding configurable as you suggested would be a welcome addittion.

Oh no! I forgot to remove `picture_panel` after the ui rewrite. That module is completely obsolete and was replaced by `picture_widget`.

With that said most if not all input handling is done inside the `picture_widget` may not be very clean, the input handling could be in a separate module instead calling higher level functions from the picture widget like `next_image()` and `fit_img_to_window()` and such.

To get back to bindings for toggling full-screen, it's a bit different than regular keyboard input becaouse most importantly it's a double click, or with more general terms two of the same type of input happening in short succession. I think the biggest challange is to find a good way to represent this in the bindings section of the configuration. As an initial proposal I think the following could be a how this is expressed
```toml
# two times the left mouse button
toggle_fullscreen = "double:lmb"
# two times alt+f
toggle_fullscreen = "double:alt+f"
# two times ':' but this probably won't happen (space can be ommited)
toggle_fullscreen = "double: :"
```
