### ISSUE TITLE
Specify background color

### ISSUE THREAD

**Issue by Aloso** [ArturKovacs/emulsion#52]
I prefer a darker background color in the dark theme. One solution is to make this configurable, e.g.

```toml
[dark_theme]
background = "#202020"
```

Emulsion represents colors as `[f32; 4]` internally, but converting a hexadecimal color to `[f32; F]` is straightforward.
