### ISSUE TITLE
Customize key command

### ISSUE THREAD

**Issue by Geobert** [ArturKovacs/emulsion#7]
I'm not using qwerty so customization of navigation keys would be cool :)

At least adding space bar as alias to right arrow to match Irfanview behaviour (hard to change a habit gained after decades of using Irfanview… ^^')

**Comment by ArturKovacs** [comment]
The most straightforward way to implement this would be to add fields for each action to the cfg.toml something like
```toml
prev_img = "A"
next_img = "D"
fit_img = "F"
```
There could also be graphical interface to set these within emulsion but that would take some time to do right so for now I'd like to keep it simle and just stick to the config file.

**Comment by Geobert** [comment]
I'm very fine with no GUI for that for now :) 

Instead of one key only, maybe an array of keys?

**Comment by ArturKovacs** [comment]
Please see the readme [here](https://github.com/ArturKovacs/emulsion/blob/c7416795cadfc87f54c47e5c8ecd7d309f01c725/README.md) and tell me if this is what you were looking for. If you pull and test that state on your computer I will be even happier.

**Comment by Geobert** [comment]
Yeah that exactly what I need :D I pull the branch, but it doesn't work:
```toml
dark = true
win_w = 1474
win_h = 971
win_x = -1706
win_y = 32

[bindings]
img_next = ["space", "right"]
img_prev = ["a", "left"]
img_orig = ["q"]
img_fit = ["f"]
img_del = ["delete"]
pan = ["n"]
play_anim = ["alt+a", "alt+v"]
play_present = ["p"]
play_present_rnd = ["alt+p"]
```

pressing `space` does nothing

**Comment by Geobert** [comment]
with this:
```toml
[window]
dark = true
win_w = 580
win_h = 558
win_x = -1349
win_y = 57

[bindings]
img_del = ["delete"]
img_fit = ["f"]
img_next = ["space", "i", "right"]
img_orig = ["q"]
img_prev = ["a", "left"]
pan = ["x"]
play_anim = ["alt+a", "alt+v"]
play_present = ["p"]
play_present_rnd = ["alt+p"]
```

I can go to next with "i" and pan with "x" but "space" doesn't work
